name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov
    
    - name: Setup Speech-to-Text credentials
      run: |
        echo '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}' > /tmp/speech-to-text-key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/speech-to-text-key.json" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        pytest --cov=app tests/
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    # Setup gcloud CLI with deployment service account
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        
    # Add deployment status check
    - name: Verify deployment
      id: deploy
      run: |
        if [ $? -eq 0 ]; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::failure"
          exit 1
        fi

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ steps.deploy.outputs.status }}" == "success" ]; then
          echo "Deployment successful!"
        else
          echo "Deployment failed!"
          exit 1
        fi
