name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker
      run: |
        gcloud auth configure-docker

    - name: Build and Push Docker image
      env:
        PROJECT_ID: openlabel-lab-firebase
      run: |
        docker build -t gcr.io/${PROJECT_ID}/gramfocus:${{ github.sha }} .
        docker push gcr.io/${PROJECT_ID}/gramfocus:${{ github.sha }}

    - name: Deploy to Cloud Run
      env:
        PROJECT_ID: openlabel-lab-firebase
      run: |
        gcloud run deploy gramfocus \
          --image gcr.io/${PROJECT_ID}/gramfocus:${{ github.sha }} \
          --platform managed \
          --region us-central1 \
          --project ${PROJECT_ID} \
          --allow-unauthenticated

    - name: Verify deployment
      id: deploy
      env:
        PROJECT_ID: openlabel-lab-firebase
      run: |
        DEPLOY_STATUS=$(gcloud run services describe gramfocus --platform managed --region us-central1 --project ${PROJECT_ID} --format='get(status.conditions[0].status)')
        if [ "$DEPLOY_STATUS" = "True" ]; then
          echo "::set-output name=status::success"
        else
          echo "::set-output name=status::failure"
          exit 1
        fi

    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ steps.deploy.outputs.status }}" == "success" ]; then
          echo "Deployment successful!"
        else
          echo "Deployment failed!"
          exit 1
        fi
